
    # Copyright IBM Corp. All Rights Reserved.
    #
    # SPDX-License-Identifier: Apache-2.0
    #
    
    
    ################################################################################
    #
    #   Section: Organizations
    #
    #   - This section defines the different organizational identities which will
    #   be referenced later in the configuration.
    #
    ################################################################################
    Organizations:
        - &undefined
            # DefaultOrg defines the organization which is used in the sampleconfig
            # of the fabric.git development environment
            Name: undefinedMSP
    
            # ID to load the MSP definition as
            ID: undefinedMSP

            MSPDir: crypto-config/peerOrganizations/undefined.example.com/msp

            # Policies defines the set of policies at this level of the config tree
            # For organization policies, their canonical path is usually
            #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('undefinedMSP.admin', 'undefinedMSP.peer', 'undefinedMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('undefinedMSP.admin', 'undefinedMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('undefinedMSP.admin')"
    
            AnchorPeers:
                # AnchorPeers defines the location of peers which can be used
                # for cross org gossip communication.  Note, this value is only
                # encoded in the genesis block in the Application section context
                - Host: peer0.undefined.example.com
                  Port: 31051